version: '3.4'

services:
  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    container_name: blog.api
    build:
      context: .
      dockerfile: Prosiglieri.Blog.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      blog.database:
        condition: service_healthy

  blog.database:
    image: postgres:latest
    container_name: blog.database
    environment:
      - POSTGRES_DB=blogposts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/blog-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5